name: Rodar Pipeline Ouvidoria

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 10 * * *"   # 08:00 UTC
    - cron: "0 15 * * *"  # 14:00 UTC
    - cron: "0 19 * * *"  # 20:00 UTC

jobs:
  rodar_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Criar arquivo de credenciais
        run: echo "${{ secrets.GDRIVE_CRED_JSON }}" > ouvidoria-tratamento-dados.json

      - name: Rodar script Python
        run: python main.py
