# Render Configuration - Dashboard Ouvidoria
# Este arquivo pode ser usado para configurar o deploy no Render

services:
  - type: web
    name: ouvidoria-dashboard
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production

